### ISSUE TITLE
error in operatingData / map request [504 / 500]

### ISSUE THREAD

**Issue by domstick** [a1development/ioBroker.boschindego#34]
![image](https://user-images.githubusercontent.com/39016069/128189207-5c857125-fede-404c-b4f8-d6a718c35271.png)

Version: 0.9.12
Indego: M700+ (2020)
Firmware: 27176

**Comment by domstick** [comment]
![image](https://user-images.githubusercontent.com/39016069/128199400-dce4ccc3-9c90-435a-bd38-7ec2dd33e826.png)

**Comment by a1development** [comment]
500 and 504 are Error Codes where the service did not respond correctly. This could have different reasons. E.g. connection problems, server errors etc. 
The Adapter should check periodicaly and try to reconnect. 
Did id reconnect by it self after some time?
There is not much i can do about this, exect .. not show this message :)

**Comment by domstick** [comment]
Ok then it is a problem within the Bosch API / Server - their servers are having problems regularily at the moment ;)
Maybe you could edit the log message to something like: "Bosch server responded with error code 500" then it would be clear.
Other than that your adapter works like a charm! No problems with new firmware. Also tried ioBroker Admin 5.1.21 - works perfectly!

**Comment by a1development** [comment]
Thanks! Yes. I will make some moddification to the error logging. 
I think it should try to recover by it self .. if that does not work .. only then the a error message should be shown. 
Did it recover in your case after some time? 
Did you see alot of this errors?

**Comment by domstick** [comment]
![image](https://user-images.githubusercontent.com/39016069/128208845-5a743a78-4201-4ce7-b7cb-c51090565b92.png)
Didn't recover yet. But status codes and messages are still getting updated.

**Comment by a1development** [comment]
OK interessting! Thanks! How long did the errors show in total?

**Comment by domstick** [comment]
Several hours in total until now.
Just did a reboot of the machine running ioBroker. It seems to have fixed the errors:
![image](https://user-images.githubusercontent.com/39016069/128224506-6dd7c930-1163-445c-b1d9-3d22813cffab.png)
In comparison to my logs above with the errors, there was no "bot stopped" immediately after "connect ok"

**Comment by a1development** [comment]
Uh. Ok. That s strange. I investigated further and made some changes. The Adapter should force a reconnect ( refresh auth etc ) if something like this happens. I pushed a new version with this changes. 
Did this situation happen multiple times, or just this once? Would be nice if you could test with this version.

**Comment by domstick** [comment]
![image](https://user-images.githubusercontent.com/39016069/128325085-41e9fb63-27e5-40b5-9e99-0fde2c941d94.png)
This message was shown when I logged into ioBroker just now (0.9.12).
Installing the new version now and testing. Thanks Markus!

**Comment by domstick** [comment]
![image](https://user-images.githubusercontent.com/39016069/128325449-25eddf65-be11-4a9f-a698-a6400dd7cc15.png)
Version 0.9.12

**Comment by domstick** [comment]
![image](https://user-images.githubusercontent.com/39016069/128326109-047f184a-7acb-477e-8f9d-b5234f0fd047.png)
Installed Version 0.9.13. No errors so far. I'll keep reporting.

**Comment by domstick** [comment]
![image](https://user-images.githubusercontent.com/39016069/128335392-62d1bd57-a548-422b-859f-ba2aee91365f.png)
Version 0.9.13

Seems like the Bosch servers are heaving trouble...

**Comment by domstick** [comment]
![image](https://user-images.githubusercontent.com/39016069/128354595-8d584dcb-f8e0-404a-ad2b-07c65d0c4aed.png)

**Comment by a1development** [comment]
Hmm .. very strange. Never got that during my extensive testing. 429 doesn t look to good. 
What kind of connection do you have? 
Could you try to test if there are problems with your internet connection
Open a commad prompt " click on windows logo and type "cmd" and start it. 
There type:
ping google.de /t
This will ping the google website every seconde. 
You can let this run for quite some time. And if you encounter more errors ( exept the 429 ) press "ctrl + c" or "strg + c" 
After that you will see how many requests where dropped.

**Comment by a1development** [comment]
![image](https://user-images.githubusercontent.com/1611103/128372672-629d4d3d-dc31-416e-8a37-525e142b87d7.png)
It will look like this. 
How are you using the adapter? Do you open your app on your mobile often?
Does this run on multiple machines?

**Comment by domstick** [comment]
Yes, I'm opening the app very often recently.
Your Adapter runs on one machine only.
Did the ping test on that machine:
![image](https://user-images.githubusercontent.com/39016069/128394226-3f99c43b-14e9-459e-be05-198d5e52b64f.png)
No packets lost, and no errors in ioBroker logs since the manual instance reload.
I recently installed Admin 5.1.21 Beta for ioBroker and did no other major changes.
It's the first time I encountered that problem.
I assume I produced too many requests to Bosch servers and maybe got some sort of softban perhaps.
I'll try to provoke it again and going to see what the ping test does while getting errors.

**Comment by domstick** [comment]
> Yes, I'm opening the app very often recently.
I'm doing some testing and optimizations to the mower itself, so I'm constantly checking its position etc.
Therefore, in theory, I'm probably producing "unnatural" amounts of requests.

**Comment by domstick** [comment]
I don't know whats going on. No packet loss during that timeframe.
The adapter ran fine today until I started the mobile app, while being on the same ip as the machine running ioBroker.
![image](https://user-images.githubusercontent.com/39016069/128608518-02a4e8e0-c1fd-46bf-9d65-e2f15f0e0fd4.png)

**Comment by domstick** [comment]
I reinstalled 0.9.12.
While there are still some error 500 left, I don't get any 429 or force close of the adapter by iobroker.
I assume the immediate reconnects of 0.9.13 are too much load on the Bosch servers leading to error 429.

**Comment by a1development** [comment]
OK i made some changes and uploaded 0.9.14. 
The reconnect will be handled more like in the version 0.9.12. 

Still strange that you see this errors. I don t get any. Even if i use the mobile app. 
Are you using android or ios?

**Comment by domstick** [comment]
> Still strange that you see this errors. I don t get any. Even if i use the mobile app.
> Are you using android or ios?

It's very strange..
Hasn't been a Problem before installing Admin 5, JS Controller 3.3 and Indegos new firmware 27176.
Obviously one of those three must have broken my personal setup.
Or my account at Bosch is flagged for some reason. Maybe I should contact them for clearance.

I use the Android app. Even with the App is sometimes get a blank map instead of my garden app, wich would add to the assumption that it's a server error on Boschs side.

I'm hoping this is not a waste of your time, but maybe that's still interresting for the error handling of the adapter?

With 0.9.14 I'm getting the same iobroker error as with .13:
![image](https://user-images.githubusercontent.com/39016069/128708855-7579b1c5-8f30-434e-9ad1-e9a5fbd835d0.png)

The logs leading to that forced termination by iobroker:
![image](https://user-images.githubusercontent.com/39016069/128709559-85af896c-507b-4116-831b-37b0455ab6c6.png)

I'm reading it that way:
Adapter gets 504, tries to reconnect immediately, followed by a 429 "softban" because of the many fast connection attempts.

**Comment by a1development** [comment]
Hmm .. Just to be sure. 
When i update the Adapter in my system i:
1. stop the adapter
2. delete the adapter
3. go to the adapter List, and delete the adapter shown there
4. In Adapter List  click on gitub icon. Go to "Custom" ( Benutzerdefiniert ) and paste in the Adapter URL "https://github.com/a1development/ioBroker.boschindego" and click on install
5. Install the Adapter on the machine and enter credentials. 
6. Start adapter. 

I just tested this adapter on Admin5 with JS Control 3.3 and everything works good.
I did start the bot .. opend my android app.. looked at the map .. switched different screens etc.. Everything works fine. 
The difference is that i am using the indego 400 s+ but that should be nearly the same. 

Could you please follow the instruction for uninstall / install again .. even if you are doing this already. AND restart your iobroker ? 

The theory i have is, due to the 504 errors ( gateway timeout ) .. i think there might be some network issues between your iobroker and the bosch service, that could have many reasons. ( bad internet connection, bad routing from your ips, etc ) 
Timeout could mean that maybe some requests are running to long and pile up. So that at the end .. too many connections are open. 
When i debug this at my machines, this does not happen, but i don t get 504s. 

I just changed every request, so that each request can only run once before it can be started again. So the request needs to be completed or failed before it can be started again. 

Could you please try Version 0.9.15. I have not had the time to test it for long, but the tests i made worked good.

**Comment by domstick** [comment]
> Could you please try Version 0.9.15. I have not had the time to test it for long, but the tests i made worked good.

Thank you so much!
Did a complete uninstall of the adapter and rebooted the iobroker host, before installing 0.9.15.
No errors so far.
![image](https://user-images.githubusercontent.com/39016069/128730792-906bd792-1208-4529-935a-232bf32496aa.png)
I'll stress test it a bit with extensive use of the app in parallel.

**Comment by domstick** [comment]
Got errors after some time with 0.9.15.
I have problems with the android app at the same time ("Indego offline" in the app).
So I think it's a problem with the server at  Bosch....
The frequency of the reconnects of the adapter seems right now. Not getting 429 and the adapter isn't force closed by iobroker.
![image](https://user-images.githubusercontent.com/39016069/128743434-3c95966f-0f8b-4277-bdb1-ad616d59f206.png)

**Comment by a1development** [comment]
OK good. So the 429s are fixed with the latest changes. 
The 429 ( too many requests ) and the 504 (gateway timeout) are errors i can not reproduce nor did anyone else report this issues. 
So there does not seem to be a general problem with the servers or the adapter, otherwise everyone else would experience this from time to time. 
I still have the hunge that something is off with your setup / network or connection to the bot.
From my side i can do much about the 504 errors. 

Was your bot moving during the errors? 
So each request ended in a 504?

Just out of curiosity. 
Could you try to restart your bot in the following sequence:
- switch off the bot ( hardware switch ) 
- pull the bot out of the charging station ( still switched off )
- unplug the charing station for 10 minutes
- (close the android app / or if you want to try everything, uninstall / reinstall )
- plug in the charging station AFTER 10 minutes :)
- now - outside of the station -> switch on the bot and then
- move the bot to the charging contacts in the station
- proceed with startup ( enter pin etc )

Maybe the 504 errors are timeouts because your bot does not respond in time ( there is a mobile network connection / no wifi etc ) inside your bot. Perhaps it has a bad connection. I had some connection problems with my bot, even when it showed a good connection in the display. After doing this routine on 2 days .. it helped. This was a tip from the hotline.

**Comment by domstick** [comment]
> OK good. So the 429s are fixed with the latest changes.
> Was your bot moving during the errors?

Yes, it was operating normally and keeps updating the iobroker objects like state text.
So the adapter and my scripts work with 0.9.15!
There are juste these errors in the logs, but the adapter works fine otherwise.

> Just out of curiosity.
> Could you try to restart your bot in the following sequence:

I'll test it later today and will keep you updated.

Thank you - even more because it seems like its not a common problem!

**Comment by domstick** [comment]
> Just out of curiosity.
> Could you try to restart your bot in the following sequence:
> 
> * switch off the bot ( hardware switch )
> * pull the bot out of the charging station ( still switched off )
> * unplug the charing station for 10 minutes
> * (close the android app / or if you want to try everything, uninstall / reinstall )
> * plug in the charging station AFTER 10 minutes :)
> * now - outside of the station -> switch on the bot and then
> * move the bot to the charging contacts in the station
> * proceed with startup ( enter pin etc )

Did that with uninstalling the android app.
Unfortunately no change in behaviour. I'll ask Bosch if they or their GSM-provider are having trouble.

![image](https://user-images.githubusercontent.com/39016069/128879941-4f367d1f-8a6e-4d88-af2b-795a0eb1d4ea.png)

**Comment by a1development** [comment]
Yes,,, but still. Odd that it does not happen on other machines. At least not that massive. 
Intersting that your Map errors disapeared after the reset of the bot. I guess it s a mix of server and a connection to your bot. 
Or additionaly something with your network connection. ( using proxy, running ioBroker on a vm ? )
I just updated the version to 0.9.16 for you. It s just a slight change. 
Before, on each error triggered a reconnect. Now i am ignoring the 504 for operationData ( still showing up in the logs, but not triggering a new connect ) 
I want to see if this results in a diferent behavior. 
Could you please uninstall / reinstall?
What is shown in your datapoints under operatingData?

**Comment by domstick** [comment]
> I let him do a full charge and downgrade the firmware (need to test some others things as well with old firmware).

No errors so far with old firmware 25116. So it seems like there are even more problems with the new one ;)

No errors were thrown by the adapter after software update to FW 26116:
![image](https://user-images.githubusercontent.com/39016069/128943380-46423377-50ca-4b3e-9448-f52aad8ddbef.png)

The states during that timeframe (including unknown ones):
![image](https://user-images.githubusercontent.com/39016069/128943237-c0fd48e7-681b-427f-8271-e12826b549e2.png)

**Comment by a1development** [comment]
OK that looks good. So it was the new firmware. Hmm .. 
But when there are other users complaining ( that are not using the adapter .. as this is nothing official, nor do i know if they are too happy about it ) .. i hope they will change the firmware and fix the problems.
Thanks for testing. If you like you can keep me updated on this issue.

**Comment by domstick** [comment]
> Thanks for testing. If you like you can keep me updated on this issue.

Thank you for taking the time! I hope it was worth it just a little bit at least to improve error handling in case of server errors.
